[2023-11-02T10:16:14.083-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: economics_data_pipeline.pull_and_save_fred_data manual__2023-11-02T15:16:09.374359+00:00 [queued]>
[2023-11-02T10:16:14.086-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: economics_data_pipeline.pull_and_save_fred_data manual__2023-11-02T15:16:09.374359+00:00 [queued]>
[2023-11-02T10:16:14.087-0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-02T10:16:14.094-0500] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): pull_and_save_fred_data> on 2023-11-02 15:16:09.374359+00:00
[2023-11-02T10:16:14.102-0500] {standard_task_runner.py:57} INFO - Started process 97827 to run task
[2023-11-02T10:16:14.108-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'economics_data_pipeline', 'pull_and_save_fred_data', 'manual__2023-11-02T15:16:09.374359+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/economics_data_pipe.py', '--cfg-path', '/var/folders/3l/sjtljk5j23ng0k_w12x41kh80000gn/T/tmpov92yst1']
[2023-11-02T10:16:14.109-0500] {standard_task_runner.py:85} INFO - Job 34: Subtask pull_and_save_fred_data
[2023-11-02T10:16:14.136-0500] {task_command.py:416} INFO - Running <TaskInstance: economics_data_pipeline.pull_and_save_fred_data manual__2023-11-02T15:16:09.374359+00:00 [running]> on host macbook-pro-207.local
[2023-11-02T10:16:14.168-0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='hermesadmin' AIRFLOW_CTX_DAG_ID='economics_data_pipeline' AIRFLOW_CTX_TASK_ID='pull_and_save_fred_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-02T15:16:09.374359+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-02T15:16:09.374359+00:00'
[2023-11-02T10:16:14.170-0500] {fred_utils.py:34} INFO - Fetching data from URL: https://api.stlouisfed.org/fred/series/observations?series_id=GDP&api_key=5c78bd237c041fcf6bebdae4f8e05905&file_type=json
[2023-11-02T10:37:21.165-0500] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-11-02T10:37:21.170-0500] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 97827. PIDs of all processes in the group: [97827]
[2023-11-02T10:37:21.171-0500] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 97827
[2023-11-02T10:38:21.215-0500] {process_utils.py:149} WARNING - process psutil.Process(pid=97827, name='Python', status='running', started='10:16:14') did not respond to SIGTERM. Trying SIGKILL
[2023-11-02T10:38:21.218-0500] {process_utils.py:86} INFO - Sending the signal Signals.SIGKILL to group 97827
[2023-11-02T10:38:21.226-0500] {process_utils.py:79} INFO - Process psutil.Process(pid=97827, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='10:16:14') (97827) terminated with exit code Negsignal.SIGKILL
[2023-11-02T10:38:21.227-0500] {standard_task_runner.py:172} ERROR - Job 34 was killed before it finished (likely due to running out of memory)
