Traceback (most recent call last):
  File "/Users/dimz/EconWizard/hermesvirtual/lib/python3.8/site-packages/psutil/_psosx.py", line 346, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/dimz/EconWizard/hermesvirtual/lib/python3.8/site-packages/psutil/_common.py", line 480, in wrapper
    raise raise_from(err, None)
  File "<string>", line 3, in raise_from
  File "/Users/dimz/EconWizard/hermesvirtual/lib/python3.8/site-packages/psutil/_common.py", line 478, in wrapper
    return fun(self)
  File "/Users/dimz/EconWizard/hermesvirtual/lib/python3.8/site-packages/psutil/_psosx.py", line 373, in _get_kinfo_proc
    ret = cext.proc_kinfo_oneshot(self.pid)
ProcessLookupError: [Errno 3] assume no such process (originated from sysctl(kinfo_proc), len == 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dimz/EconWizard/hermesvirtual/lib/python3.8/site-packages/psutil/__init__.py", line 361, in _init
    self.create_time()
  File "/Users/dimz/EconWizard/hermesvirtual/lib/python3.8/site-packages/psutil/__init__.py", line 719, in create_time
    self._create_time = self._proc.create_time()
  File "/Users/dimz/EconWizard/hermesvirtual/lib/python3.8/site-packages/psutil/_psosx.py", line 346, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/dimz/EconWizard/hermesvirtual/lib/python3.8/site-packages/psutil/_psosx.py", line 471, in create_time
    return self._get_kinfo_proc()[kinfo_proc_map['ctime']]
  File "/Users/dimz/EconWizard/hermesvirtual/lib/python3.8/site-packages/psutil/_psosx.py", line 351, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=4397)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dimz/EconWizard/hermesvirtual/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/Users/dimz/EconWizard/hermesvirtual/lib/python3.8/site-packages/airflow/__main__.py", line 59, in main
    args.func(args)
  File "/Users/dimz/EconWizard/hermesvirtual/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/dimz/EconWizard/hermesvirtual/lib/python3.8/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
  File "/Users/dimz/EconWizard/hermesvirtual/lib/python3.8/site-packages/airflow/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
  File "/Users/dimz/EconWizard/hermesvirtual/lib/python3.8/site-packages/airflow/cli/commands/webserver_command.py", line 504, in webserver
    monitor_gunicorn(gunicorn_master_proc.pid)
  File "/Users/dimz/EconWizard/hermesvirtual/lib/python3.8/site-packages/airflow/cli/commands/webserver_command.py", line 459, in monitor_gunicorn
    GunicornMonitor(
  File "/Users/dimz/EconWizard/hermesvirtual/lib/python3.8/site-packages/airflow/cli/commands/webserver_command.py", line 213, in start
    self._wait_until_true(
  File "/Users/dimz/EconWizard/hermesvirtual/lib/python3.8/site-packages/airflow/cli/commands/webserver_command.py", line 159, in _wait_until_true
    while not fn():
  File "/Users/dimz/EconWizard/hermesvirtual/lib/python3.8/site-packages/airflow/cli/commands/webserver_command.py", line 214, in <lambda>
    lambda: self.num_workers_expected == self._get_num_workers_running(),
  File "/Users/dimz/EconWizard/hermesvirtual/lib/python3.8/site-packages/airflow/cli/commands/webserver_command.py", line 153, in _get_num_workers_running
    workers = psutil.Process(self.gunicorn_master_proc.pid).children()
  File "/Users/dimz/EconWizard/hermesvirtual/lib/python3.8/site-packages/psutil/__init__.py", line 332, in __init__
    self._init(pid)
  File "/Users/dimz/EconWizard/hermesvirtual/lib/python3.8/site-packages/psutil/__init__.py", line 373, in _init
    raise NoSuchProcess(pid, msg='process PID not found')
psutil.NoSuchProcess: process PID not found (pid=4397)
